package exception.inner;

public class InnerTryDivProject {

	public static void main(String[] args) {

		Division.div();
	}
}
